import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "@/components/Utilities/Providers/QueryProvider";
import { NextUiProvider } from "@/components/Utilities/Providers/NextUiProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-white">
        <QueryProvider>
          <NextUiProvider>{children}</NextUiProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
